<?xml version="1.0" encoding="utf-8"?><Database Name="QuizV1" Class="QuizLINQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=YO-PC;Initial Catalog=QuizV1;Integrated Security=True" SettingsObjectName="QuizLite.Properties.Settings" SettingsPropertyName="QuizV1ConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Questions" Member="Questions">
    <Type Name="Question">
      <Column Name="QuestionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Question" Member="Question1" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Solution" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Option1" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Option2" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Option3" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Option4" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="QuestionTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="QuestionType_Question" Member="QuestionType" ThisKey="QuestionTypeID" OtherKey="QuestionTypeID" Type="QuestionType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QuestionTypes" Member="QuestionTypes">
    <Type Name="QuestionType">
      <Column Name="QuestionTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="QuestionType_Question" Member="Questions" ThisKey="QuestionTypeID" OtherKey="QuestionTypeID" Type="Question" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FacebookID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Surname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Score" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="AnsweredRight" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AnsweredFailed" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nick" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Photo" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>