<?xml version="1.0" encoding="utf-8"?><Database Name="QuizV1" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=YO-PC;Initial Catalog=QuizV1;Integrated Security=True" SettingsObjectName="SpreadSheetImporter.Properties.Settings" SettingsPropertyName="QuizV1ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Questions" Member="Questions">
    <Type Name="Question">
      <Column Name="QuestionID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Question" Member="Question1" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Solution" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Option1" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Option2" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Option3" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Option4" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="QuestionTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>